In [14]:
import numpy as np
import pandas as pd
df = pd.read_csv('day2.txt', sep=' ', names=['direction', 'amount'])
x = df[df.direction == 'forward'].amount.sum()
y = df[df.direction == 'down'].amount.sum() - df[df.direction == 'up'].amount.sum()
x, y, x*y

(2034, 702, 1427868)

In [28]:
(df
 .assign(aim_delta=pd.Series(np.select([df.direction == 'down', df.direction == 'up'], [df.amount, -df.amount])),
         aim=lambda df_: df_.aim_delta.cumsum(),
         x=lambda df_: df_.amount.where(df_.direction=='forward').cumsum().ffill().astype(int),
         y=lambda df_: (df_.amount.where(df_.direction=='forward')*df_.aim).cumsum().ffill().astype(int),
         x_y = lambda df_:df_.x*df_.y
        )
)
#df[df.direction == 'down'].amount - df[df.direction == 'up'].amount

    direction  amount  aim_delta  aim     x       y         x_y
0     forward       2          0    0     2       0           0
1        down       2          2    2     2       0           0
2     forward       6          0    2     8      12          96
3     forward       8          0    2    16      28         448
4        down       8          8   10    16      28         448
..        ...     ...        ...  ...   ...     ...         ...
995      down       6          6  707  2027  766047  1552777269
996        up       4         -4  703  2027  766047  1552777269
997   forward       2          0  703  2029  767453  1557162137
998        up       1         -1  702  2029  767453  1557162137
999   forward       5          0  702  2034  770963  1568138742

[1000 rows x 7 columns]